login/urls.py
from django.urls import path
from . import views

app_name='login'
'''urlpatterns = [
    path('index', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('<int:num>/', views.userlist, name='usuarios'),
]
'''

miSitio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
#    path('', include('login.urls')),
    path('', include('pyapp.urls')),
    path('admin/', admin.site.urls),
]

pyapp/urls.py
from django.urls import path
from . import views

app_name='pyapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('login_attempt/', views.login_attempt, name='login_attempt'),
    path('ajax_test/', views.ajax_test, name='ajax_test'),
    path('register/', views.register, name='new-user'),
    path('register_action/', views.register_action, name='register_action'),
    path('logout_action/', views.logout_action, name='logout_action'),
    path('my_notes/', views.my_notes, name='my_notes'),
]

login/models.py
from django.db import models
import datetime

# Create your models here.
class User(models.Model):
	username = models.CharField(max_length=50)
	password = models.CharField(max_length=50)
	fechaCreacion = models.DateTimeField(auto_now_add=True, blank=True)
	
	def __str__(self):
		return f"{self.username} creado el {self.fechaCreacion.strftime('%d, %b, %Y')}"

pyapp/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
import datetime

# Create your models here.
class User(models.Model):
	username = models.CharField(max_length=50)
	password = models.CharField(max_length=50)
	fechaCreacion = models.DateTimeField(auto_now_add=True, blank=True)

	def __str__(self):
		return f"{self.username} creado el {self.fechaCreacion.strftime('%d, %b, %Y')}"

class Note(models.Model):
  noteTitle = models.CharField(max_length=50)
  noteBody = models.TextField()
  noteCreatedDate = models.DateTimeField(editable=False)
  noteUpdatedDate = models.DateTimeField()
  enabled = models.BooleanField()
  userId = models.ForeignKey(User, on_delete=models.CASCADE)

  '''Overload of save method'''
  def save(self, *args, **kwargs):
    #On dave Update timestamps
    if not self.id:
      self.noteCreatedDate=timezone.now()
    self.noteUpdatedDate=timezone.now()
    return super(Note, self).save(*args, **kwargs)

  def __str__(self):
    return f"{self.noteTitle}\n{self.noteBody}\n{self.noteCreatedDate}"

login/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

from .models import User

# Create your views here.
def login(request):
        return HttpResponse(f"1+1={11}")
def index(request):
	usuarios = User.objects.order_by('id')[:5]
	template = loader.get_template('login/index.html')
	context = {'usuarios': usuarios}
        #return render(request, 'login/index.html', context)
	return HttpResponse(template.render(context, request))
def userlist(request, num):
        return HttpResponse("Total de usuario %s." % num)

pyapp/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.core import serializers

from .models import User, Note

# Create your views here.
def is_ajax(request):
  return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def login(request):
    login_template = loader.get_template('pyapp/login.html')
    index_template = loader.get_template('pyapp/index.html')
    context = {'title':'Nuevo Usuario'}
    if 'logged_in'not in request.session:
        return HttpResponse(login_template.render(context, request))
    else:
        return HttpResponse(index_template.render(context, request))
def index(request):
    usuarios = User.objects.order_by('id')
    template = loader.get_template('pyapp/index.html')
    context = {'usuarios': usuarios}
    return HttpResponse(template.render(context, request))
def ajax_test(request):
  message="not ajax"
  if is_ajax(request=request):
    '''Python dictionary to temporary store data'''
    new_note = {
      'title':request.POST.get('noteTitle'),
      'body':request.POST.get('noteBody'),
      'uname':request.session['logged_in']
    }
    try:
      u = User.objects.get(username=new_note['uname'])
      n = Note(noteTitle=new_note['title'], noteBody=new_note['body'], enabled=True, userId=u)
      n.save()
    except Exception as e:
      return JsonResponse({'msg':str(e)})
    else:
      return JsonResponse({'msg':'success'})
def register(request):
    template = loader.get_template('pyapp/register.html')
    context = {'title':'Nuevo Usuario'}
    return HttpResponse(template.render(context, request))
def register_action(request):
    try:
        nuevoUsuario = User(username=request.POST['username'], password=request.POST['password'], fechaCreacion=timezone.now())
        nuevoUsuario.save()
    except (KeyError):
        return HttpResponseRedirect(reverse('pyapp:login', args=()))
    else:
        return HttpResponseRedirect(reverse('pyapp:index', args=()))
def login_attempt(request):
    uname = request.POST['username']
    pwd = request.POST['password']
    try:
        tmp_Usr = User.objects.get(username = uname)
        if tmp_Usr.username == uname and tmp_Usr.password == pwd:
            request.session['logged_in']=uname
            request.session.set_expiry(0)
            return HttpResponseRedirect(reverse('pyapp:index', args=()))
        else:
            return HttpResponse('<script>alert("Revisa los datos introducidos");</script>')
    except:
        return HttpResponse('<script>alert("Revisa los datos");</script>')
    else:
        return render(request, 'pyapp/login.html')
def logout_action(request):
    del request.session['logged_in']
    return HttpResponseRedirect(reverse('pyapp:index', args=()))
def my_notes(request):
  notes = Note.objects.order_by('id')
  template = loader.get_template('pyapp/my_notes.html')
  context = {'notes':notes}
#return HttpResponseRedirect(reverse('pyapp:my_notes', args=()))
  if is_ajax(request=request):
    notes_Json=serializers.serialize('json',notes)
    return JsonResponse(notes_Json, safe=False)
  else:
    return HttpResponse(template.render(context, request))

login/templates/login/index.html
<!DOCTYPE html>
<html>
	<head>
	   <meta charset="utf-8">
	   <title>Nopal Systems Inc.</title>
	</head>
	<body>
		{%if usuarios %}
			<ul>
			    {%for user in usuarios%}
				<li><a href="{% url 'login:usuarios' user.id%}">{{user.username}}</a></li>
			    {%endfor%}
			</ul>
		{%else%}
			<p>No hay usuarios que mostrar</p>
		{%endif%}
		<h3>Designed by: Lemi </h3>
	</body>
</html>

pyapp/templates/pyapp/index.html
{%extends './layout.html'%}

{% block content %}
  <h2>Usuarios Creados</h2>

    {% if usuarios %}
        <ul>
        {%for user in usuarios%}
            <li><a>{{user.username}}</a></li>
        {%endfor%}
        </ul>
    {%else%}
        <p>No hay usuarios que mostrar</p>
    {%endif%}
{%endblock%}

pyapp/templates/pyapp/layout.html
<!doctype html>
<html lang="en">
{% load define_action %}
{% comment 'check if session is active' %}
{% endcomment %}
{% if 'logged_in' in request.session %}
  {% define True as logged_in %}
  {% define request.session.logged_in as uname %}
{% endif %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- choose one -->
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    <title>Practica | Python</title>
  </head>
  <body class="d-flex flex-column min-vh-100">
    {%include './navbar.html'%}
    <div class="container">
        {% block content %}

        {% endblock %}
    {% if not logged_in %}
<!--      <p><a href="{% url 'pyapp:login' %}">Iniciar Sesión</a></p>
      <p><a href="{% url 'pyapp:new-user' %}">Registrarse</a>
-->
    {% endif %}
    </div>
    <!-- Footer -->
<footer class="mt-auto bg-secondary style="background-color: #e3f2fd;"">

  <!-- Copyright -->
  <div class="text-center py-3">© 2022 No Copyright:
    <a href=""> Designed Using Bootstrap </a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% include './js/drkMde.js' %}
  </body>
</html>

pyapp/templates/pyapp/login.html
{%extends './layout.html'%}
{%block content%}
<form action="{% url 'pyapp:login_attempt'%}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" name="password" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

pyapp/templates/pyapp/my_notes.html
{% extends './layout.html' %}

{% block content%}
{%load static%}
<div class="row">
 <div class="col-sm-6 py-3 w-auto">
   <p>
    <button class="btn btn-success" type="button" data-bs-toggle="collapse" data-bs-target="#newNote" aria-expanded="false" aria-controls="newNote">
      <i data-feather="plus-circle"></i>
      <span>New</span>
    </button>
    <button class="btn btn-primary disabled" type="button"><i data-feather="check-circle"></i>
      <span>Select All</span>
    </button>
    <button class="btn btn-secondary" id="refreshNotes"><i data-feather="refresh-ccw"></i></button>
   </p>
   <form class="collapse" id="newNote" method="POST">
     {% csrf_token %}
    <div class="col-sm-6 py-2">
     <div class="card">
      <div class="card-header">
        <input class="w-100" type="text" placeholder="Title" name="noteTitle" maxlength="50" id="noteTitle"/>
     </div>
     <div class="card-body">
       <p class="card-text">
        <label  class="text-muted">Write your note down Here</label>
        <div class="overflow-auto form-control" contenteditable="true" aria-multiline="true" id="noteBody"></div>
       </p>
       <a href="#" class="btn btn-primary" id="saveNewNote"><i data-feather="save"></i>
        <span> Save </span></a>
       <a href="#" class="btn btn-danger" id="dropNewNote"><i data-feather="trash-2"></i>
         <span>Cancel</span></a>
     </div>
    </div>
  </div>
 </form>
<div id="savedNotes">
{%if notes%}
{%for note in notes %}
  <div class="col-sm-6 py-2">
    <div class="card" id="{{id}}">
     <div class="card-header">
        {{note.noteTitle}}
     </div>
      <div class="card-body">
        <p class="card-text">
          {{note.noteBody}}</p>
        <a href="#" class="btn btn-primary"><i data-feather="edit-2"></i>
          <span> Edit </span></a>
        <a href="#" class="btn btn-danger"><i data-feather="x-circle"></i>
          <span>Delete</span></a>
      </div>
      <div class="card-footer text-muted">
        Created on: {{note.noteCreatedDate}}
      </div>
   </div>
 </div>
{%endfor%}
{%endif%}
  </div>
</div>
</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script type="text/javascript" src="{%static 'pyapp/new_note.js'%}"></script>
<script>feather.replace();</script>
{%endblock%}

pyapp/templates/pyapp/my_profile.html
{% extends './layout.html' %}

pyapp/templates/pyapp/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand d-inline" href="{%url 'pyapp:index'%}">
      <i data-feather="coffee" style="width: 60px;"></i>
      <span class="ps-2">My App</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i data-feather="tool"></i>Tools
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href=""><i data-feather="type"></i>HTML formatter
                <small class="text-muted position-absolute ms-2">Beta</small></a>
            </li>
            <li>
             <a class="dropdown-item" href=""><i data-feather="book-open"></i> Json Finder
              <small class="text-muted position-absolute ms-2">Beta</small></a>
            </li>
          </ul>
        </li>
{%if logged_in %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	    <i data-feather="user"></i>{{uname}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#"><i data-feather="calendar"></i> My Calendar</a></li>
            <li><a class="dropdown-item" href="{% url 'pyapp:my_notes'%}"><i data-feather="book"></i>My Notes</a></li>
            <li><a class="dropdown-item" href="#">
              <i data-feather="settings"></i>
              Settings</a>
            </li>
            <li><a class="dropdown-item" href="{%url 'pyapp:logout_action'%}">
              <i data-feather="log-out"></i>
              Log out</a>
            </li>
{% else %}
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i data-feather="user"></i><span>Not logged in</span>
           </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{%url 'pyapp:login'%}">
             <i data-feather="log-in"></i>Login</a></li>
	     <li class="ps-4"><small class="text-muted">Don't have an account?</small></li>
            <li><a class="dropdown-item" href="{%url 'pyapp:new-user'%}">
             <i data-feather="user-plus"></i>Register</a></li>
{% endif %}
            <li><hr class="dropdown-divider"></li>
           <li><div class="dropdown-item">
<!-- boton modo oscuro -->
             <i data-feather="sun" class="d-inline me-2"></i>
              <div class="form-check form-switch d-inline-block">
                <input class="form-check-input float-none" style="margin-top: 0.35em" type="checkbox" id="flexSwitchCheckDefault" onchange="mo()">
              </div>
              <div class="d-inline-block"><i data-feather="moon"></i></div>
            </div>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
            <i data-feather="bar-chart-2"></i>
            Admin Panel</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-success" type="submit"><i data-feather="search"></i></button>
      </form>
    </div>
    </div>
</nav>
<script>
      feather.replace()
</script>

pyapp/templates/pyapp/new_text.html
{%extends './layout.html'%}

pyapp/templates/pyapp/register.html
<!DOCTYPE html>
<html>
	<head>
	   <meta charset="utf-8">
	   <title>{{ django|title }}</title>
	</head>
	<body>
		<form action="{% url 'pyapp:register_action' %}" method="post">
		{% csrf_token %}
			<label for="username" name="Username or emailaddress"/>
				Username:
			</label>
			<input type="text" placeholder="Enter your username, phone or emailadress" name="username"/>
			<label for="password" value=="Password"/>
				Password: 
			</label>
			<input type="password" placeholder="Enter your password" name="password"/>
			<input type="submit" value="Registrar"/>
		</form>
		<h3>Designed by: Lemi </h3>
	</body>
</html>

pyapp/templates/pyapp/sidebar.html
<button class="btn btn-light end-0"  type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" aria-controls="offcanvas">
  <i data-feather="menu"></i>

</button>

<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas" aria-labelledby="offcanvasLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasLabel">Menú</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div>
      Some text as placeholder. In real life you can have the elements you have chosen. Like, text, images, lists, etc.
    </div>
    <div class="dropdown mt-3">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown">
        Dropdown button
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
      </ul>
      <hr class="dropdown-divider">
      <!-- switch de modo oscuro -->
      <div class="form-check form-switch">
        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" onchange="mo()">
        <label class="form-check-label" for="flexSwitchCheckDefault">Modo oscuro</label>
      </div>
    </div>
  </div>
</div>

<script>
      feather.replace()
</script>

pyapp/templates/pyapp/text_view.html
{%extends './layout.html'%}